import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/internal/header";
import Footer from "@/components/internal/footer";
import { fetchData } from "./utils/service";
import { GET_CONTACT, GET_PRACTICE_HEADER } from "./utils/service/index.query";
import {
  ClientContactUsResponse,
  ClientPracticeAreasResponse,
} from "./utils/interface/index.query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LawFirm",
  description: "Generated by create next app",
};

const contactData = await fetchData<ClientContactUsResponse>({
  query: GET_CONTACT,
  path: "data.getClientContactUsPageContent",
  variables: {
    input: {
      limit: 50,
      order: "desc",
      orderBy: "_id",
      skip: 0,
    },
  },
});

const pubData = await fetchData<ClientPracticeAreasResponse>({
  query: GET_PRACTICE_HEADER,
  path: "data.findAllClientPracticeAreas",
  variables: {
    input: {
      limit: 50,
      order: "desc",
      orderBy: "_id",
      skip: 0,
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-offwhite`}
      >
        <Header contactData={contactData} pubData={pubData} />
        {children}
        <Footer contactData={contactData} pubData={pubData} />
      </body>
    </html>
  );
}
